
const actions = {
  UPDATE_BODY: "UPDATE_BODY",
  REGISTER_USER: "REGISTER_USER",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  EDIT_DETAILS: "EDIT_DETAILS",
  UPDATE_USER:"UPDATE_USER",
};

export {actions}