
const actions = {
  UPDATE_BODY: "UPDATE_BODY",
  REGISTER_USER: "REGISTER_USER",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  EDIT_DETAILS: "EDIT_DETAILS",
  TOGGLE_DOCTORS_RECORD: "TOGGLE_DOCTORS_RECORD",
  LOGIN_FAIL: "LOGIN_FAIL",
  SET_OBJECT_DATA: "SET_OBJECT_DATA",
  UPDATE_PAGE: "UPDATE_PAGE",
  SET_LOADING: "SET_LOADING",
  UPDATE_REQUESTS: "UPDATE_REQUESTS",
  SET_CURRENT_RECORD: "SET_CURRENT_RECORD",
  SET_ACCEPTED_PATIENTS: "SET_ACCEPTED_PATIENTS",
  SET_CURRENT_EDIT:"SET_CURRENT_EDIT"
};

export {actions}