version: '3'
services:
  app:
    container_name: mobidoc_records_service
    restart: always
    build: .
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - RECORD_ACCESS_SECRET=${RECORD_ACCESS_SECRET}
      - HASH_SECRET=${HASH_SECRET}
      - DOCTOR=${DOCTOR}
      - PATIENT=${PATIENT}
    ports:
      - '3050:3050'
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'